### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by nhiller1** [jdimodica1/project#1]
Hi Jonathan,
I really like your website - your use of images and the external link is great.  I also like the FAQ page because of the design and because of how informative it is.

Technical suggestions:
- making the navigation bar larger/providing more padding to help it take up more space (chasing the color of it might also help it stand out from the rest of the page)
- when you use the call to action “here” for signing up, make it lowercase if it is in a sentence and notice the spacing of it is different than the “normal” words

Content suggestions:
- adding a little more about how the company got started might help take up more space on the home page and interest the user. You could also utilize this information in an “About Us” tab.
-I love your use of pictures but I think adding a little bit more content so that pictures are not the majority of the page would be nice

Overall, great job!

**Comment by jdimodica1** [comment]
Thank you for the suggestions, I will consider all of it!
