### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by mparo1** [jdimodica1/project#3]
Hi Jonathan,

I like your website and how you used it to promote your own company! I also like your color scheme throughout, its very appealing.

Technical:
1. Add titles to your images
2. Mix up the alignment of some of your pages and have more going across to fill the length of the pages

Content:
1. Maybe add an "About" page/transform your FAQ questions page to have information about how your company came to be.
2. Add some videos of some past events possibly

Great job and I can't wait to see your next website update!

**Comment by jdimodica1** [comment]
Thank you for the suggestions, I will consider these changes!
