### ISSUE TITLE
Two Technical Suggestions

### ISSUE THREAD

**Issue by gavinfarnan** [jdimodica1/project#4]
Firstly, I think that it is great that you are using this opportunity to grow your business and to have another avenue that customers can interact with your site. My two suggestions in terms of some technical or bugs suggestions are: 
1. I think that it would look much better if you made it so your font was just a little bigger for the text in between the pictures. Perhaps you could use the h3 header. 
2. I think it would also be beneficial if you could link your actual website so that people could sign up via this website. Maybe you could add a link on the "marketplace" page that linked the place where they could sign up.

**Comment by jdimodica1** [comment]
Thank you for the suggestions, I will consider this!
